version: "3"
services:
  server:
    build:
      context: .
    environment:
      DB_USERNAME: root
      DB_PASSWORD: test123
      DB_HOST: mysql
      DB_DATABASE: almedia
      DB_PORT: 3306
    depends_on:
      - mysql
    volumes:
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: almedia
    ports:
      - 3306:3306